### ISSUE TITLE
APP CRASHES

### ISSUE THREAD

**Issue by SultanAyubi360** [Vnjvibhash/WhatsApp-Status-Downloader#1]
when navigate back from settings fragment to status fragment app crashes. why so please? Handle it

**Comment by Vnjvibhash** [comment]
After giving Permission or without permission please be little specific

**Comment by Vnjvibhash** [comment]
Which mobile phone are you using? May I know the model number? Because I'm
using Motorola and Pixel both are working properly. I couldn't find any
issue yet.
After giving Permission or without permission please be little specific


Vivek Kumar
Software Engineer
CSE | BE

**Comment by SultanAyubi360** [comment]
if not give permission and when we navigate back while press back it crashes. I  am using emulator pixel 7a api 27.

**Comment by SultanAyubi360** [comment]
check yourself when you press device back icon from settings or from whatsapp business fragment.
