### ISSUE TITLE
Issue on changing of theme

### ISSUE THREAD

**Issue by SultanAyubi360** [Vnjvibhash/WhatsApp-Status-Downloader#2]
when we change theme it restarts main activity but not change bottom nav option to first option it stay there where we change theme.
Means for example i am on settings fragment and in bottom nav settings is active then i change theme main activity recreates it load fragments again from start but on bottom nav settings will be active still it have to change to first bottom nav option.
I hope you understand

**Comment by Vnjvibhash** [comment]
This Issue Has been Resolved.
